"""add free_orders_enabled to settings

Revision ID: 0c6d3d3b47ee
Revises: 8fb00ac9bd10
Create Date: 2026-04-13 20:54:25.046876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c6d3d3b47ee'
down_revision: Union[str, Sequence[str], None] = '8fb00ac9bd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add free_orders_enabled if it doesn't exist
    op.add_column('system_settings', sa.Column('free_orders_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Fix master_profiles.is_accredited nullability if needed
    op.execute("ALTER TABLE master_profiles ALTER COLUMN is_accredited SET NOT NULL")
    op.execute("ALTER TABLE master_profiles ALTER COLUMN is_accredited SET DEFAULT FALSE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'free_orders_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('master_profiles', 'is_accredited',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('service_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('service_categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
