"""add_experience_to_master

Revision ID: a1c05651093a
Revises: f394c01eac32
Create Date: 2026-04-01 17:16:19.042463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c05651093a'
down_revision: Union[str, Sequence[str], None] = 'f394c01eac32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_profiles', sa.Column('experience', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_profiles', 'experience')
    # ### end Alembic commands ###
