"""Add message to bids

Revision ID: b4cd72a02cd4
Revises: 2cb7e3278834
Create Date: 2026-04-02 12:12:55.720106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cd72a02cd4'
down_revision: Union[str, Sequence[str], None] = '2cb7e3278834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'message')
    # ### end Alembic commands ###
